### ISSUE TITLE
Feature Request: set number of columns

### ISSUE THREAD

**Issue by PhantomCloak** [sergeystoma/updoot#12]
It would be good if we can specify column count in fixed view, I think this feature could improve experience by a lot because there is no way in the internet to show reddit saved posts as a single column thus more than one column makes thumbnails thinner than usual for people using saved posts as a image gallery like me It's painful to open every image for each browser tab, so instead of 3 fixed size column I would specify to it (like one column) and view all post's thumbnail as nearly full size like reddit's default post view

**Comment by sergeystoma** [comment]
Added one and two column modes.
