### ISSUE TITLE
Feature Request: Add a saved posts counter

### ISSUE THREAD

**Issue by Leon-ok** [sergeystoma/updoot#25]
It would be really handy, because the way I count it now is Ctrl+F and searching for reddit.com, i.redd.it, gfycat etc. This feature would really speed it up!

**Comment by sergeystoma** [comment]
Added total + filtered counters. There was already a per-subreddit counter under settings.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/585437/127586248-63e42087-914b-4322-b285-e034fe79af43.png">

(I like cheese...)
