### ISSUE TITLE
Bug: updoot signs out after some time

### ISSUE THREAD

**Issue by Leon-ok** [sergeystoma/updoot#30]
Every time I go to updoot, it asks me to log in with reddit and give access. After some time, I have to log in and give access again! It doesn't remember that I already logged in and gave access.

**Comment by snarkbe** [comment]
I have the same issue.
I actually thought it was Reddit that forces a frequent login to avoid having apps with long access time. Or it's in the way the auth request is done, as I don't have this behavior with other third-party reddit apps.

**Comment by sergeystoma** [comment]
Yeah, that was a bit of an oversight. The login session cookie had a session lifetime, and wasn't kept around for much longer. Added expiration of 1 year.

🤞 reddit token expiration works as expected still, guess we'll find out shortly 😬
