### ISSUE TITLE
Updoot stuck in Login Request For Permission Loop

### ISSUE THREAD

**Issue by Acche314** [sergeystoma/updoot#36]
Every time it asks me to login into to reddit with Updoot.app, it goes to the login page (I've been logged in, and I've tried relogging with no success) to request for permission and I press "allow" before this would head me back to Updoot.app saved posts page and it would work. But now it just briefly loads for like .5 secs and sends me back to the Updoot.app page and tells me to sign back in with reddit instead of the Updoot saved posts page. I'm not sure what happened between it working and not, maybe a computer update or something. Is there any fix for this at all?

**Comment by sergeystoma** [comment]
@Acche314 Are you using any adblockers/no-script solutions? I've tried to replicate what you are seeing to no avail yet. 
Wonder if it works for you in private window too?

**Comment by Acche314** [comment]
Okay so I had no scripts running and I had disabled any adblocks to test that and at the time it did nothing. But just recently Updoot started working again like before. And I cant seem to recreate the issue either. So maybe it had to with a Chrome update or maybe a Windows 11 update I'm not sure. It is quite odd, but thanks for trying to look into it. It does seem to work now lol
