### ISSUE TITLE
Feature Request: Import Reddit csv data/file?

### ISSUE THREAD

**Issue by rubik11** [sergeystoma/updoot#41]
Is it possible to have function to import csv data/file from [Reddit data request](https://www.reddit.com/settings/data-request)?

**Comment by sergeystoma** [comment]
@rubik11 Unfortunately no, Updoot doesn't store the data itself and relies on the Reddit API to expose saved posts and comments instead. An alternative would be to import the data back into another account saved list, but that's not a part of the planned functionality at the moment.
