### ISSUE TITLE
Links contained in a Reddit post open in the same tab

### ISSUE THREAD

**Issue by snarkbe** [sergeystoma/updoot#42]
While clicking on the title on a Reddit post opens it in another tab, clicking on an hyperlink inside the content of the post opens it in the same tab, replacing Updoot.

![image](https://user-images.githubusercontent.com/38499432/162504697-20989ee7-fab7-4f2c-9a41-581777cab7e2.png)

**Comment by sergeystoma** [comment]
Fixed, embedded links should open in a new tab.
