### ISSUE TITLE
Feature Request: Set theme to Auto by default

### ISSUE THREAD

**Issue by jrstrunk** [sergeystoma/updoot#52]
Love the site, great work on it. Was there a reason that the theme was set to light by default and not auto by default now that it is an option? In the code either the value in the store could start as "auto" or when the theme is retrieved from the store it could have "auto" as the fallback instead of "light".

If there was no reason for keeping light as the default, I would love to see auto set to the default.

**Comment by jrstrunk** [comment]
Actually looking at the way the store restores the settings, it would be better to set the fallback for the `theme` computed val in `app` to "auto" when the store value is null instead of setting the default value in the store to "auto".

**Comment by sergeystoma** [comment]
@jrstrunk Amazing, thank you! I prefer the Light side, so it was mostly no special thoughts about it. `auto` definitely makes more sense
