### ISSUE TITLE
Feature Request: number of saved posts total and for each subreddit

### ISSUE THREAD

**Issue by snarkbe** [sergeystoma/updoot#8]
It would be nice to have somewhere on the main screen the account name for which the saved posts are displayed and the total number of saved posts.

And in the filter windows, in the subreddit list, to have the number of saved posts for each subreddit.
For instance by having the number between parenthesis after the name: `r/funny (13)`

**Comment by sergeystoma** [comment]
Added saved post counts

![image](https://user-images.githubusercontent.com/585437/100266062-3420f980-2f1f-11eb-9634-b65ae225a540.png)
